CREATE TABLE User (
  UserID VARCHAR(10) PRIMARY KEY,
  UserName VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Account VARCHAR(20) NOT NULL
);
CREATE TABLE Product (
  ProductID INT AUTO_INCREMENT PRIMARY KEY,
  ProductName VARCHAR(50) NOT NULL,
  Price DECIMAL(10, 2) NOT NULL,
  FeeRate DECIMAL(5, 2) NOT NULL
);
CREATE TABLE LikeList (
  SN INT AUTO_INCREMENT PRIMARY KEY,
  OrderName VARCHAR(50) NOT NULL,
  Account VARCHAR(20) NOT NULL,
  TotalFee DECIMAL(10, 2) NOT NULL,
  TotalAmount DECIMAL(10, 2) NOT NULL,
  ProductID INT NOT NULL,
  Quantity INT NOT NULL,
  FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);
